version: '3.1'

services:
    user-cli:
        build: ../user-cli/
        depends_on:
            - user-service
    user-service:
        build: .
        ports:
          - 50053:50051
        environment:
          MICRO_ADDRESS: ":50051"
          MICRO_REGISTRY: "mdns"
          DB_NAME: "postgres"
          DB_HOST: "database"
          DB_PORT: "5432"
          DB_USER: "postgres"
          DB_PASSWORD: "postgres"
        depends_on:
          - database
    database:
        image: postgres
        environment:
            POSTGRES_PASSWORD: postgres
        ports:
          - 5432:5432
